name: Docker Build and Push
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: docker/build-push-action@v1.1.0
      name: Build and push phabricator
      with:
        username: ${{ Secrets.DockerUsername }}
        password: ${{ Secrets.DockerPassword }}
        repository: cole2026/phabricator
        tag_with_sha: true
        dockerfile: Dockerfile
    - uses: docker/build-push-action@v1.1.0
      name: Build and push phabricator
      with:
        username: ${{ Secrets.DockerUsername }}
        password: ${{ Secrets.DockerPassword }}
        repository: cole2026/phabricator-daemon
        tag_with_sha: true
        dockerfile: Dockerfile
